andreystar/portfolio/src/main/webapp/index.html
andreystar/portfolio/src/main/webapp/style.css

Add used technologies to projects.

---

ancar/portfolio/pom.xml
ancar/portfolio/src/main/java/com/google/sps/servlets/DataServlet.java

https://github.com/googleinterns/step/blob/master/walkthroughs/week-3-server/step-1-servlets-walkthrough.md

Finish step-1 of the week-3 tutorial.

---

ancar/portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
ancar/portfolio/src/main/webapp/index.html
ancar/portfolio/src/main/webapp/script.js
ancar/portfolio/src/main/webapp/style.css

Here's the link for the task: https://github.com/googleinterns/step/blob/master/walkthroughs/week-3-server/step-2-fetch-walkthrough.md

Do the step-2 of the week-3 tutorial.

---

ancar/portfolio/pom.xml
ancar/portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
ancar/portfolio/src/main/webapp/index.html
ancar/portfolio/src/main/webapp/script.js
ancar/portfolio/src/main/webapp/style.css

Added a hardcoded list of 3 cities parsed as a JSON object in DataServlet.java and script.js fetches the JSON string from it.
https://github.com/googleinterns/step/blob/master/walkthroughs/week-3-server/step-3-json-walkthrough.md

Finish step-3, parsing json.

---

ancar/portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
ancar/portfolio/src/main/webapp/index.html
ancar/portfolio/src/main/webapp/script.js

https://github.com/googleinterns/step/blob/master/walkthroughs/week-3-server/step-4-post-walkthrough.md
Add a form to submit comments on my portfolio page. Atm the comments are just shown as a list on the page, done just for the purpose of testing.

Finish step-4 of week-3.

---

ancar/portfolio/pom.xml
ancar/portfolio/src/main/java/com/google/sps/servlets/DataServlet.java

https://github.com/googleinterns/step/blob/master/walkthroughs/week-3-server/step-5-datastore-walkthrough.md
Works fine, checked the /_ah/admin page.

Store comments as entities in Datastore.

---

ancar/portfolio/src/main/java/com/google/sps/servlets/DataServlet.java

Finish the step-5 of the week-3 tutorial.

Show all the existing comments on the page from Datastore.

---

ancar/portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
ancar/portfolio/src/main/java/com/google/sps/servlets/DeleteCommentsServlet.java

Also added a file that was missing before : DeleteCommentsServlet.java

Fix the issue with empty comments and the style suggestions of Andrey.

---

ancar/.gitignore
ancar/portfolio/src/main/webapp/script.js

Also, updated the .gitignore file as a bunch of files/binaries from the walkthroughs were untracked.

Fixed the bug with html-type comments.

---

ancar/portfolio/src/main/webapp/index.html
ancar/portfolio/src/main/webapp/script.js
ancar/portfolio/src/main/webapp/style.css

How it used to look:
How it looks now:
Next I'll handle the styling of the comment section.

Rearrange the page.

---

ancar/portfolio/src/main/webapp/index.html
ancar/portfolio/src/main/webapp/style.css

How it used to look:
How it looks now:
Thinking of deploying this version, and then trying to add something more on the comments. Then if everything works, maybe deploying it again. :)

More CSS-styling :(

---

ancar/portfolio/src/main/webapp/script.js
ancar/portfolio/src/main/webapp/style.css

As Stofee suggested in the last PR

Resolve the fixed sizes.

---

ancar/walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
ancar/walkthroughs/week-5-tdd/project/src/test/java/com/google/sps/FindMeetingQueryTest.java

As a part of this tutorial:
https://github.com/googleinterns/step/blob/master/walkthroughs/week-5-tdd/project/calendar-walkthrough.md

Do the algorithm for scheduling a meeting between multiple people.

---

step-release-vis/src/assets/2CandDone_TwoSnapshots.json
step-release-vis/src/assets/AllDoneNewCand_TwoSnapshots.json
step-release-vis/src/assets/CandDecreaseAndDone_ThreeSnapshots.json
step-release-vis/src/assets/CandDoneAtEachTimestamp_ThreeSnapshots.json
step-release-vis/src/assets/CandDoneGraduallyAndTwoNew_FourSnapshots.json
step-release-vis/src/assets/CandDone_TwoSnapshots.json
step-release-vis/src/assets/NewCandComeAndGo_ThreeSnapshots.json
step-release-vis/src/assets/NewCandZeroJobs_TwoSnapshots.json
step-release-vis/src/assets/NewCand_TwoSnapshots.json
step-release-vis/src/assets/StartWith4FinishWith1_FiveSnapshots.json

Create sample JSON files with different scenarios in just one environment.
As discussed with Laura and Andrey, we have a constant amount of total jobs and time goes from 0 to 1000 at the moment.

Create mock data

---

step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/models/Data.ts
step-release-vis/src/app/models/Polygon.ts
step-release-vis/src/app/services/environment.ts

* Add data class for JSON
* Add default polygon color

Add JSON Data class.

---

step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/services/environment.ts
step-release-vis/src/app/services/file.ts
step-release-vis/src/app/services/file_test.ts

* Add a FileService which reads contents of a file with an http.get request
* Subscribe to the returned Observable in the Environment component
_Testing Observables requires research. Will add it later not to block other people._

Add reading JSON from file.

---

step-release-vis/src/app/components/grid/base.ts
step-release-vis/src/app/components/grid/canvas/canvas.ts
step-release-vis/src/app/components/grid/canvas/canvas_test.ts
step-release-vis/src/app/components/grid/svg/svg.ts
step-release-vis/src/app/components/grid/svg/svg_test.ts
step-release-vis/src/app/services/param.ts
step-release-vis/src/app/services/param_test.ts
step-release-vis/src/testing/ActivatedRouteStub.ts

* Update param service to utilize Observables. Previously the param service would take a snapshot of the params
* Update grid components to use the changed service

Update param service to utilize Observables.

---

step-release-vis/.prettierrc.json
step-release-vis/mvn/pom.xml
step-release-vis/package-lock.json
step-release-vis/package.json
step-release-vis/src/app/app-routing.module.ts
step-release-vis/src/app/app.component.spec.ts
step-release-vis/src/app/app.component.ts
step-release-vis/src/app/app.module.ts
step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environment/environment_test.ts
step-release-vis/src/app/components/grid/base.ts
step-release-vis/src/app/components/grid/canvas/canvas.ts
step-release-vis/src/app/components/grid/canvas/canvas_test.ts
step-release-vis/src/app/components/grid/svg/svg.ts
step-release-vis/src/app/components/grid/svg/svg_test.ts
step-release-vis/src/app/components/home/home.ts
step-release-vis/src/app/components/home/home_test.ts
step-release-vis/src/app/models/Polygon.ts
step-release-vis/src/app/services/file.ts
step-release-vis/src/app/services/file_test.ts
step-release-vis/src/app/services/param.ts
step-release-vis/src/app/services/param_test.ts
tips.md

* Add support for _Prettier_ plugin and _.prettierrc.json_ with formatting rules ([source](https://github.com/google/gts/blob/master/.prettierrc.json))
* Add setup steps to _tips.md_
* Reformat files

Add .prettier plugin and reformat code.

---

step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environment/environment_test.ts

* Scale the received polygons to screen, preserving ratio
* Assign a random color to each polygon

Add polygon processing.

---

step-release-vis/src/app/app-routing.module.ts
step-release-vis/src/app/app.component.spec.ts
step-release-vis/src/app/app.module.ts
step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/home/home.html
step-release-vis/src/app/components/home/home_test.ts

* Add _/env_ route for EnvironmentComponent
* Add link to EnvironmentComponent to homepage.
* Fix imports which caused warnings during tests

Add routing for Environment component.

---

step-release-vis/src/app/components/environment/environment.html
step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environment/environment_test.ts
step-release-vis/src/app/components/grid/canvas/canvas_test.ts
step-release-vis/src/app/components/grid/svg/svg_test.ts
step-release-vis/src/testing/EnvironmentServiceStub.ts

* Add hover listeners, which update the polygon's `highlight` flag
* Base polygon's opacity on the state of the flag
* Add a test for hover events

Add hover listeners for polygon opacity. 

---

step-release-vis/src/app/services/environment_test.ts
step-release-vis/src/app/services/file_test.ts
step-release-vis/src/testing/FileServiceStub.ts

* Add a test for FileService
* Add FileServiceStub
* Add test for getPolygons()
- Currently the json files describe one env and getPolygons() is expected to return data for one env. Later with the parent component being introduced, the test will be updated.

Add test for FileService and getPolygons().

---

step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environment/environment_test.ts
step-release-vis/src/app/components/environments/environments.html
step-release-vis/src/app/components/environments/environments.ts
step-release-vis/src/app/components/environments/environments_test.ts

* Make child width and height configurable
* Add test for parent component which checks if dimensions for children were assigned
* Update test for child component, since the dimensions are now input parameters

Make child width and height configurable.

---

step-release-vis/src/app/models/Candidate.ts
step-release-vis/src/app/services/candidate.ts
step-release-vis/src/app/services/candidate_test.ts

These are used for linking the appearences of one candidate in multiple environments.

Add Candidate model and CandidateService

---

step-release-vis/src/app/components/environment/environment_test.ts
step-release-vis/src/app/models/Data.ts
step-release-vis/src/app/services/environment.ts
step-release-vis/src/app/services/environment_test.ts
step-release-vis/src/assets/2CandDone_TwoSnapshots.json
step-release-vis/src/assets/AllDoneNewCand_TwoSnapshots.json
step-release-vis/src/assets/AllFilesMerged.json
step-release-vis/src/assets/CandDecreaseAndDone_ThreeSnapshots.json
step-release-vis/src/assets/CandDoneAtEachTimestamp_ThreeSnapshots.json
step-release-vis/src/assets/CandDoneGraduallyAndTwoNew_FourSnapshots.json
step-release-vis/src/assets/CandDone_TwoSnapshots.json
step-release-vis/src/assets/NewCandComeAndGo_ThreeSnapshots.json
step-release-vis/src/assets/NewCandZeroJobs_TwoSnapshots.json
step-release-vis/src/assets/NewCand_TwoSnapshots.json
step-release-vis/src/assets/StartWith4FinishWith1_FiveSnapshots.json
step-release-vis/src/testing/FileServiceStub.ts

* Move from snake_case to camelCase in JSON files in order to stay consistent with the naming.
_TODO(andreystar): update go/step-release-vis-data on approval_

Move from snake_case to camelCase in JSON files.

---

step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environment/environment_test.ts
step-release-vis/src/app/components/environments/environments.ts
step-release-vis/src/app/components/environments/environments_test.ts
step-release-vis/src/app/models/Candidate.ts
step-release-vis/src/testing/CandidateServiceStub.ts

* Make use of CandidateService in parent and child components
* Update tests to pass with new layout
* Add TODO for parent component test

Utilize CandidateService.

---

step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environment/environment_test.ts
step-release-vis/src/app/components/environments/environments.html
step-release-vis/src/app/components/environments/environments.ts
step-release-vis/src/app/components/environments/environments_test.ts
step-release-vis/src/testing/CandidateServiceStub.ts
step-release-vis/src/testing/EnvironmentServiceStub.ts

* Add test for parent component.

Add test for parent component. Close #176 - Make use of Candidate classes.

---

step-release-vis/src/app/components/environments/environments.html
step-release-vis/src/app/components/environments/environments.ts
step-release-vis/src/app/components/form/dataSubmissionForm.ts
step-release-vis/src/app/components/form/dataSubmissionForm_test.ts
step-release-vis/src/app/components/home/home.html
step-release-vis/src/app/services/candidate.ts
step-release-vis/src/app/services/file.ts
step-release-vis/src/app/services/file_test.ts
step-release-vis/src/testing/FileServiceStub.ts

* Replace router param to file with localStorage contents
* Display submission link if no file is found
* Make localStorage query return an Observable

 Integrate data submission form with parent component.

---

step-release-vis/src/app/components/environment/environment.css
step-release-vis/src/app/components/environment/environment.html
step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environment/environment_test.ts
step-release-vis/src/app/components/environments/environments.html
step-release-vis/src/app/components/environments/environments.ts
step-release-vis/src/app/components/form/dataSubmissionForm.ts
step-release-vis/src/app/models/TimelinePoint.ts
step-release-vis/src/assets/AllFilesMerged.json

* Update json file to have real timestamps
* Calculate timeline points based on start and end times (TODO)
* Pass calculated points to child components
* Display the timeline using the timeline points

Add timeline points to graph.

---

step-release-vis/src/app/components/environment/environment.css
step-release-vis/src/app/components/environment/environment.html
step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environments/environments.ts
step-release-vis/src/app/components/environments/environments_test.ts
step-release-vis/src/app/services/candidate.ts
step-release-vis/src/app/services/candidate_test.ts
step-release-vis/src/assets/AllFilesMerged.json
step-release-vis/src/testing/CandidateServiceStub.ts

* Move scale method to service
* Add timeline points calculation
* Display start/end timestamps and one every 200px

Add timeline points calculation.

---

step-release-vis/src/app/components/form/dataSubmissionForm.css
step-release-vis/src/app/components/form/dataSubmissionForm.html
step-release-vis/src/app/components/form/dataSubmissionForm.ts
step-release-vis/src/app/components/form/dataSubmissionForm_test.ts

* If text field is not empty, use the data from it.
* Otherwise, take the contents of the selected file and store them as a string in localstore.

Update form to support json file upload.

---

step-release-vis/src/app/components/environments/environments.ts
step-release-vis/src/app/components/environments/environments_test.ts
step-release-vis/src/app/services/file.ts
step-release-vis/src/app/services/proto_buffer.ts
step-release-vis/src/app/services/proto_buffer_test.ts
step-release-vis/src/testing/FileServiceStub.ts
step-release-vis/src/testing/ProtoBufferServiceStub.ts

* Add binary file reading
* Use read info to display environments

Read data from binary proto file.

---

step-release-vis/src/app/components/environment/environment.html
step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environment/environment_test.ts
step-release-vis/src/app/components/environments/environments.html
step-release-vis/src/app/components/environments/environments.ts
step-release-vis/src/app/components/environments/environments_test.ts
step-release-vis/src/app/services/environment.ts
step-release-vis/src/app/services/environment_test.ts

_Mostly refactor_
* Add start/end timestamp fields to parent and component. Set to last available week.
* Update EnvService to receive an array of snapshots
* Update tests

Add start/end timestamp fields. Update tests.

---

step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environment/environment_test.ts
step-release-vis/src/app/components/environments/environments.ts
step-release-vis/src/app/components/environments/environments_test.ts
step-release-vis/src/app/services/candidate.ts
step-release-vis/src/app/services/candidate_test.ts
step-release-vis/src/testing/CandidateServiceStub.ts
step-release-vis/src/testing/EnvironmentServiceStub.ts
step-release-vis/src/testing/FileServiceStub.ts

* Filter the snapshots before calculating the polygons based on the current time range
* Sparse the filtered array leaving a set amount of snapshots
* Generate colors only for visible candidates
* Add tests

Filter and sparse the snapshots.

---

step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environment/environment_test.ts
step-release-vis/src/app/components/environments/environments.html
step-release-vis/src/app/components/environments/environments.ts
step-release-vis/src/testing/EnvironmentServiceStub.ts

* When the start/end timestamp values change in parent component, the child event listener is called
* The button shifts the timeline half a week back

Add time range update capabillity.

---

step-release-vis/package-lock.json
step-release-vis/src/app/components/environment/environment.css
step-release-vis/src/app/components/environment/environment.html
step-release-vis/src/app/components/environments/environments.css
step-release-vis/src/app/components/environments/environments.html
step-release-vis/src/app/components/environments/environments.ts
step-release-vis/src/app/components/environments/environments_test.ts
step-release-vis/src/testing/ProtoBufferServiceStub.ts

* Add start/end date/time chooser
* The date/time are displayed in local time
* Add validation
- min = first available timestamp
- max = last available timestamp
- end > start
Default:
Calendar open:

Add time range chooser.

---

step-release-vis/src/app/components/environment/environment_test.ts
step-release-vis/src/testing/DataServiceStub.ts
step-release-vis/src/testing/EnvironmentServiceStub.ts
step-release-vis/src/testing/ProtoBufferServiceStub.ts
step-release-vis/src/testing/SampleData.ts

* Place sample data in a single file and reference it from stubs

Unify sample data.

---

step-release-vis/src/app/components/environment/environment_test.ts
step-release-vis/src/app/components/form/dataSubmissionForm.ts
step-release-vis/src/app/services/dataService_test.ts
step-release-vis/src/testing/EnvironmentServiceStub.ts
step-release-vis/src/testing/SampleData.ts

* Add tests for DataService
* Update old tests

Add DataService tests. Update old tests.

---

step-release-vis/src/app/components/environment/environment.html
step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/tooltip/tooltip.css
step-release-vis/src/app/components/tooltip/tooltip.html
step-release-vis/src/app/components/tooltip/tooltip.ts
step-release-vis/src/app/components/tooltip/tooltip_test.ts

The most important part is removing the ngStyle part that was causing problems with the _"Expression has changed after it was checked" ERROR_.

Modify tooltip position implementation.

---

step-release-vis/src/app/components/environment/environment.html
step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environment/environment_test.ts
step-release-vis/src/app/components/tooltip/tooltip.css
step-release-vis/src/app/components/tooltip/tooltip.html
step-release-vis/src/app/components/tooltip/tooltip.ts
step-release-vis/src/app/components/tooltip/tooltip_test.ts
step-release-vis/src/app/models/Tooltip.ts

* Since it is not only needed for the tooltip, move the function from tooltip to environment.
* Create the currentSnapshot Input field for the tooltip component.

 (Merge after #236) Move getSnapshots to EnvironmentComponent.

---

step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environment/environment_test.ts

* Fix a bug where an already unhovered candidate would still be left as current
* Add tests for vertical line

Add tests for vertical line.

---

step-release-vis/src/app/components/form/dataSubmissionForm.ts

* Fix a problem, where the user would be redirected to env page before the data was uploaded, forcing him to reload the page

Redirect to env after localStorage item is set.

---

step-release-vis/src/app/components/environment/environment.html
step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environment/environment_test.ts
step-release-vis/src/app/components/environments/environments.html
step-release-vis/src/app/components/environments/environments.ts
step-release-vis/src/app/components/environments/environments_test.ts
step-release-vis/src/app/models/Data.ts

* Vertical line is shown in every env, not depending on current highlighted one

Show vertical line in every env.

---

step-release-vis/src/app/components/environment/environment.html
step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environment/environment_test.ts
step-release-vis/src/app/components/tooltip/tooltip.html
step-release-vis/src/app/components/tooltip/tooltip.ts
step-release-vis/src/app/models/Tooltip.ts

Refer to #240.
Had some conflicts with master branch, resolved them 1 by 1 in this branch. Its almost identical to #240.

Fix position of tooltip when the environment is clicked.

---

step-release-vis/src/app/components/environment/environment.css
step-release-vis/src/app/components/environment/environment.html

* Someone deleted my _no data_ case improvements when merging
* Add them back to html template (#255)

Add no data improvements back.

---

step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environment/environment_test.ts
step-release-vis/src/app/components/environments/environments.ts
step-release-vis/src/app/components/environments/environments_test.ts

* Make content respond to window width resize
* Do not change colors, since visible snapshots remain the same
_responding to height resize will be part of #259_

Make content adapt to screen width resize.

---

step-release-vis/src/app/services/coloringService.ts
step-release-vis/src/app/services/coloringService_test.ts

* Select color index: chooses the middle of the largest interval ending with the colors of the assigned neighbours.
* Pair candidates: after all indices are decided, select available colors and assign them to candidates according to the indices.

Select color indices and pair candidates to final colors.

---

step-release-vis/src/app/components/environment/environment.html
step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environments/environments.css
step-release-vis/src/app/components/environments/environments.html
step-release-vis/src/app/components/environments/environments.ts
step-release-vis/src/app/components/environments/environments_test.ts
step-release-vis/src/app/services/environmentService.ts

* Set the default time range start/end to min/max timestamps
* Add reset button to set time range to min/max
* Add timelines on top and bottom of envs

Add time range reset and top/bottom timelines.

---

step-release-vis/src/app/components/tooltip/tooltip.ts
step-release-vis/src/app/components/tooltip/tooltip_test.ts

Very small change to solve the bug found by Andrey this morning. :)

Resolve bug with tooltip when environments are very small.

---

step-release-vis/src/app/components/environments/environments_test.ts
step-release-vis/src/app/services/coloringService.ts
step-release-vis/src/app/services/coloringService_test.ts

* Set the constant to 75.
* Under 75 (64 cands):
* Over 75 (80 cands):

Added the second variant for coloring when the number of candidates exceeds a constant.

---

step-release-vis/src/app/components/environments/environments.css
step-release-vis/src/app/components/environments/environments.ts
step-release-vis/src/app/components/environments/environments_test.ts

* Remove random in colors
* Refactor updating lifecycle, is it was confusing
* Add start/end timestamps validation, color the form red if invalid

Add time range validation, refactor lifecycle methods.

---

step-release-vis/src/app/components/environment/environment.html
step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environment/environment_test.ts
step-release-vis/src/app/components/environments/environments.html
step-release-vis/src/app/components/environments/environments.ts

* Add drag listener to env component

Add drag listener to env component.

---

step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environment/environment_test.ts
step-release-vis/src/app/components/form/dataSubmissionForm.ts

* Freeze tooltip info when clicked. Clear localStorage
* Clear start/end timestamps is sessionStorage on data update
* Make vertical line show in empty region

Small tweaks.

---

step-release-vis/src/app/app.component.html
step-release-vis/src/app/app.module.ts
step-release-vis/src/app/components/environment/environment.html
step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environments/environments.ts
step-release-vis/src/app/components/header/header.css
step-release-vis/src/app/components/header/header.html
step-release-vis/src/app/components/header/header.ts
step-release-vis/src/app/components/header/header_test.ts
step-release-vis/src/app/components/tooltip/tooltip.css
step-release-vis/src/app/services/themeService.ts
step-release-vis/src/app/services/themeService_test.ts

Add dark mode option.

---

step-release-vis/src/app/components/environment/environment.css
step-release-vis/src/app/components/environment/environment.html
step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/tooltip/tooltip.html

* Add region highlight on drag

Add drag region highlight.

---

step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environments/environments.html
step-release-vis/src/app/components/environments/environments.ts
step-release-vis/src/app/components/environments/environments_test.ts

* Add time range update on drag.

Andreystar timerange2

---

step-release-vis/src/app/app.component.html
step-release-vis/src/app/components/environment/environment.css
step-release-vis/src/app/components/environment/environment.html
step-release-vis/src/app/components/environments/environments.html
step-release-vis/src/app/components/environments/environments.ts
step-release-vis/src/app/components/header/header.html

* Display time range and theme chooser on same line
* Fix env title display bug

Improve styling.

---

step-release-vis/src/app/services/coloringService.ts
step-release-vis/src/app/services/coloringService_test.ts

* only add edges between displayed cands

Fix coloring bug related with release edges.

---

step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environment/environment_test.ts
step-release-vis/src/app/components/environments/environments.html
step-release-vis/src/app/components/environments/environments.ts
step-release-vis/src/app/components/header/header.ts

* If the user exits the env while dragging, but returns without releasing the mouse, the drag is continued.

Add drag continuation.

---

step-release-vis/src/app/components/environment/environment.ts
step-release-vis/src/app/components/environment/environment_test.ts
step-release-vis/src/app/components/environments/environments.css
step-release-vis/src/app/components/environments/environments.html
step-release-vis/src/app/components/environments/environments.ts
step-release-vis/src/app/models/Candidate.ts
step-release-vis/src/app/services/coloringService.ts
step-release-vis/src/app/services/coloringService_test.ts

* Added form to choose vision type
* Here are is a screenshot of the page layout and colors for people with blue deficiency.

Add colorblind view.
